// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBENVXSJppDPhZqRLQpSzzuAaleOK-sKP0',
    appId: '1:155532782456:web:19fcc51854f17fb73a768d',
    messagingSenderId: '155532782456',
    projectId: 'flutterchat-d500e',
    authDomain: 'flutterchat-d500e.firebaseapp.com',
    storageBucket: 'flutterchat-d500e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6jXsjZECEqYAMWiMT9W4gqNsbedtDgNU',
    appId: '1:155532782456:android:d47d41550d8cfc5f3a768d',
    messagingSenderId: '155532782456',
    projectId: 'flutterchat-d500e',
    storageBucket: 'flutterchat-d500e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC50pXdqVfxnQe4itOCOeSIUZIwFCBuQvc',
    appId: '1:155532782456:ios:4d3dd1ed701337883a768d',
    messagingSenderId: '155532782456',
    projectId: 'flutterchat-d500e',
    storageBucket: 'flutterchat-d500e.appspot.com',
    iosBundleId: 'com.example.flutterChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC50pXdqVfxnQe4itOCOeSIUZIwFCBuQvc',
    appId: '1:155532782456:ios:4d3dd1ed701337883a768d',
    messagingSenderId: '155532782456',
    projectId: 'flutterchat-d500e',
    storageBucket: 'flutterchat-d500e.appspot.com',
    iosBundleId: 'com.example.flutterChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBENVXSJppDPhZqRLQpSzzuAaleOK-sKP0',
    appId: '1:155532782456:web:de4ca14beb348b983a768d',
    messagingSenderId: '155532782456',
    projectId: 'flutterchat-d500e',
    authDomain: 'flutterchat-d500e.firebaseapp.com',
    storageBucket: 'flutterchat-d500e.appspot.com',
  );
}
